import type { Animal, Holding, Movement, HealthEvent, MarketplaceListing, Transaction, SlaughterRecord } from "./types";

export const mockAnimals: Animal[] = [
  {
    id: "1",
    rfid: "254000123456789",
    species: "Cattle",
    breed: "Boran",
    sex: "Male",
    ageClass: "Adult",
    dateOfBirth: "2022-03-15",
    weight: 450,
    color: "White",
    currentOwner: "Kamau Mwangi",
    currentHolding: "Kiambu Dairy Farm",
    status: "Active",
    registrationDate: "2022-04-01",
    photo: "https://images.unsplash.com/photo-1580570598977-4b2412d01bbc",
    traceabilityScore: 98,
  },
  {
    id: "2",
    rfid: "254000234567890",
    species: "Goat",
    breed: "Galla",
    sex: "Female",
    ageClass: "Adult",
    dateOfBirth: "2021-06-20",
    weight: 35,
    color: "Brown and White",
    currentOwner: "Akinyi Ochieng",
    currentHolding: "Kisumu Livestock Ranch",
    status: "For Sale",
    registrationDate: "2021-07-05",
    photo: "https://images.unsplash.com/photo-1598715685267-0f45367d8071",
    traceabilityScore: 95,
  },
  {
    id: "3",
    rfid: "254000345678901",
    species: "Cattle",
    breed: "Friesian",
    sex: "Female",
    ageClass: "Young Stock",
    dateOfBirth: "2023-01-10",
    weight: 280,
    color: "Black and White",
    currentOwner: "Wanjiru Kariuki",
    currentHolding: "Nakuru Valley Dairy",
    status: "Active",
    registrationDate: "2023-02-01",
    photo: "https://images.unsplash.com/photo-1528143582951-ef14e49f4381",
    traceabilityScore: 92,
  },
];

export const mockHoldings: Holding[] = [
  {
    id: "1",
    name: "Kiambu Dairy Farm",
    owner: "Kamau Mwangi",
    location: {
      address: "Plot 234, Ruiru-Kiambu Road, Kiambu County",
      lat: -1.1714,
      lng: 36.8356,
    },
    propertyType: "Farm",
    animalCount: 150,
    area: "200 hectares",
  },
  {
    id: "2",
    name: "Kisumu Livestock Ranch",
    owner: "Akinyi Ochieng",
    location: {
      address: "Off Kisumu-Busia Highway, Kisumu County",
      lat: -0.0917,
      lng: 34.7680,
    },
    propertyType: "Farm",
    animalCount: 85,
    area: "130 hectares",
  },
  {
    id: "3",
    name: "Dagoretti Livestock Market",
    owner: "Nairobi County Government",
    location: {
      address: "Ngong Road, Dagoretti, Nairobi",
      lat: -1.2921,
      lng: 36.7419,
    },
    propertyType: "Auction",
    animalCount: 450,
  },
  {
    id: "4",
    name: "Nakuru Valley Dairy",
    owner: "Wanjiru Kariuki",
    location: {
      address: "Mai Mahiu Road, Nakuru County",
      lat: -0.3031,
      lng: 36.0800,
    },
    propertyType: "Farm",
    animalCount: 120,
    area: "180 hectares",
  },
];

export const mockMovements: Movement[] = [
  {
    id: "1",
    animalId: "1",
    animalRfid: "254000123456789",
    fromHolding: "Kiambu Dairy Farm",
    toHolding: "Dagoretti Livestock Market",
    movementDate: "2026-06-01",
    purpose: "Sale",
    permitNumber: "KE-MV-2026-001234",
    crossBorder: false,
    status: "Completed",
  },
  {
    id: "2",
    animalId: "2",
    animalRfid: "254000234567890",
    fromHolding: "Kisumu Livestock Ranch",
    toHolding: "Nakuru Valley Dairy",
    movementDate: "2026-06-05",
    purpose: "Transfer",
    permitNumber: "KE-MV-2026-001235",
    crossBorder: false,
    status: "Pending",
  },
];

export const mockHealthEvents: HealthEvent[] = [
  {
    id: "1",
    animalId: "1",
    animalRfid: "254000123456789",
    eventType: "Vaccination",
    vaccine: "FMD Vaccine",
    date: "2026-05-15",
    recordedBy: "Dr. Njoroge Macharia",
    credentialLevel: "Licensed Veterinary Officer",
    notes: "Foot and Mouth Disease vaccination completed",
    severity: "Low",
  },
  {
    id: "2",
    animalId: "2",
    animalRfid: "254000234567890",
    eventType: "Disease",
    disease: "Peste des Petits Ruminants (PPR)",
    date: "2026-05-20",
    recordedBy: "Dr. Atieno Ouma",
    credentialLevel: "Licensed Veterinary Officer",
    notes: "Treated and isolated from herd, reported to DVS",
    severity: "Medium",
  },
  {
    id: "3",
    animalId: "3",
    animalRfid: "254000345678901",
    eventType: "Vaccination",
    vaccine: "East Coast Fever (ECF)",
    date: "2026-06-01",
    recordedBy: "Dr. Kipchoge Tanui",
    credentialLevel: "Licensed Veterinary Officer",
    notes: "Routine tick-borne disease prevention",
    severity: "Low",
  },
];

export const mockListings: MarketplaceListing[] = [
  {
    id: "1",
    animalId: "2",
    animal: mockAnimals[1],
    askingPrice: 18500,
    description: "Quality Galla goat, excellent for breeding program. Healthy with complete vaccination records including PPR and deworming.",
    seller: "Akinyi Ochieng",
    listedDate: "2026-06-01",
    status: "Active",
    views: 127,
    offers: 3,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    animalId: "1",
    animalRfid: "254000123456789",
    seller: "Kamau Mwangi",
    buyer: "Nairobi Beef Processors Ltd",
    askingPrice: 85000,
    agreedPrice: 80000,
    paymentStatus: "Paid",
    saleDate: "2026-05-28",
    status: "Completed",
  },
];

export const mockSlaughterRecords: SlaughterRecord[] = [
  {
    id: "1",
    animalId: "1",
    animalRfid: "254000123456789",
    abattoirId: "KE-AB-001",
    abattoirName: "Nairobi Modern Abattoir",
    chainNumber: "NMA-2026-05432",
    carcassId: "CARC-20260601-001",
    slaughterDate: "2026-06-01",
    feedback: "Grade A carcass, good meat quality",
    verified: true,
  },
];

export const stats = {
  totalAnimals: 1247,
  activeHoldings: 156,
  marketplaceListings: 87,
  healthAlerts: 5,
  pendingTransfers: 12,
  recentTransactions: 34,
};
