# Generated by Django 6.0.6 on 2026-06-14 15:14

import CattleTrace.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.CharField(db_column='animal_ID', default=CattleTrace.models.animal_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('other', 'Other')], max_length=30)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('age_class', models.CharField(choices=[('calf', 'Calf'), ('weaner', 'Weaner'), ('yearling', 'Yearling'), ('adult', 'Adult')], max_length=30)),
                ('breed', models.CharField(max_length=255)),
                ('physical_description', models.CharField(max_length=255)),
                ('animal_status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('transferred', 'Transferred'), ('slaughtered', 'Slaughtered'), ('dead', 'Dead'), ('lost', 'Lost')], default='active', max_length=30)),
                ('estimated_live_weight', models.FloatField()),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'animals',
                'ordering': ['rfid_number'],
            },
        ),
        migrations.CreateModel(
            name='AnimalHealthWorker',
            fields=[
                ('worker_id', models.CharField(db_column='worker_ID', default=CattleTrace.models.worker_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dvs_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('worker_type', models.CharField(max_length=60)),
                ('verified', models.BooleanField(default=False)),
                ('assigned_zone', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'animal_health_workers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.CharField(db_column='holding_ID', default=CattleTrace.models.holding_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('gps_coordinates', models.CharField(max_length=100)),
                ('holding_type', models.CharField(choices=[('farm', 'Farm'), ('market', 'Market'), ('quarantine', 'Quarantine'), ('abattoir', 'Abattoir'), ('other', 'Other')], max_length=30)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('cooperative', 'Cooperative'), ('government', 'Government'), ('other', 'Other')], max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'holdings',
                'ordering': ['county', 'sub_county', 'ward', 'holding_id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(db_column='owner_ID', default=CattleTrace.models.owner_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('cooperative', 'Cooperative'), ('government', 'Government'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'owners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('event_id', models.CharField(db_column='event_ID', default=CattleTrace.models.health_event_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('disease', 'Disease'), ('death', 'Death'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=30)),
                ('disease_name', models.CharField(blank=True, max_length=255)),
                ('vaccine_name', models.CharField(blank=True, max_length=255)),
                ('treatment_given', models.CharField(blank=True, max_length=255)),
                ('cause_of_death', models.CharField(blank=True, max_length=255)),
                ('date_of_event', models.DateField()),
                ('credential_level', models.CharField(choices=[('community', 'Community'), ('technician', 'Technician'), ('veterinary_officer', 'Veterinary Officer'), ('admin', 'Admin')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(db_column='animal_ID', on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='CattleTrace.animal')),
                ('recorded_by', models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, related_name='health_events', to='CattleTrace.animalhealthworker')),
            ],
            options={
                'db_table': 'health_events',
                'ordering': ['-date_of_event', '-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='birth_holding',
            field=models.ForeignKey(db_column='birth_holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='born_animals', to='CattleTrace.holding'),
        ),
        migrations.AddField(
            model_name='animal',
            name='current_holding',
            field=models.ForeignKey(db_column='current_holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='current_animals', to='CattleTrace.holding'),
        ),
        migrations.CreateModel(
            name='Abattoir',
            fields=[
                ('abattoir_id', models.CharField(db_column='abattoir_ID', default=CattleTrace.models.abattoir_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(db_column='holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='abattoirs', to='CattleTrace.holding')),
            ],
            options={
                'db_table': 'abattoirs',
                'ordering': ['abattoir_id'],
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='owner',
            field=models.ForeignKey(db_column='owner_ID', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='CattleTrace.owner'),
        ),
        migrations.AddField(
            model_name='animal',
            name='current_owner',
            field=models.ForeignKey(db_column='current_owner_ID', on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='CattleTrace.owner'),
        ),
        migrations.CreateModel(
            name='SlaughterRecord',
            fields=[
                ('slaughter_record_id', models.CharField(db_column='slaughter_record_ID', default=CattleTrace.models.slaughter_record_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('chain_number', models.CharField(max_length=80)),
                ('carcass_feedback', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('date_of_slaughter', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abattoir', models.ForeignKey(db_column='abattoir_ID', on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='CattleTrace.abattoir')),
                ('animal', models.ForeignKey(db_column='animal_ID', on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='CattleTrace.animal')),
                ('last_holding', models.ForeignKey(db_column='last_holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='CattleTrace.holding')),
            ],
            options={
                'db_table': 'slaughter_records',
                'ordering': ['-date_of_slaughter', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(db_column='transaction_ID', default=CattleTrace.models.transaction_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30)),
                ('sale_channel', models.CharField(choices=[('direct', 'Direct'), ('market', 'Market'), ('online', 'Online'), ('auction', 'Auction'), ('other', 'Other')], max_length=30)),
                ('delivery_arrangement', models.CharField(max_length=255)),
                ('sale_date', models.DateField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(db_column='animal_ID', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='CattleTrace.animal')),
                ('buyer', models.ForeignKey(db_column='buyer_ID', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='CattleTrace.owner')),
                ('seller', models.ForeignKey(db_column='seller_ID', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='CattleTrace.owner')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-sale_date', '-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementRecord',
            fields=[
                ('movement_id', models.CharField(db_column='movement_ID', default=CattleTrace.models.movement_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('movement_date', models.DateField()),
                ('purpose_of_movement', models.CharField(choices=[('sale', 'Sale'), ('grazing', 'Grazing'), ('breeding', 'Breeding'), ('slaughter', 'Slaughter'), ('treatment', 'Treatment'), ('other', 'Other')], max_length=30)),
                ('country_crossing', models.BooleanField(default=False)),
                ('permit_number', models.CharField(blank=True, max_length=100)),
                ('movement_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(db_column='animal_rfid_number', on_delete=django.db.models.deletion.CASCADE, related_name='movement_records', to='CattleTrace.animal', to_field='rfid_number')),
                ('from_holding', models.ForeignKey(db_column='from_holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='CattleTrace.holding')),
                ('to_holding', models.ForeignKey(db_column='to_holding_ID', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='CattleTrace.holding')),
                ('linked_transaction', models.ForeignKey(blank=True, db_column='linked_transaction_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_records', to='CattleTrace.transaction')),
            ],
            options={
                'db_table': 'movement_records',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
