# Generated by Django 6.0.6 on 2026-06-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['rfid_number'], 'permissions': (('upload_animal_photo', 'Can upload animal photo'),)},
        ),
    ]
