# Generated by Django 6.0.6 on 2026-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0003_add_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
