# Generated by Django 6.0.6 on 2026-07-01 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0004_add_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='restricted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='restricted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='restriction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='credibility_level',
            field=models.CharField(choices=[('vet_verified', 'Vet Verified'), ('cahw_observation', 'CAHW Observation'), ('self_reported', 'Self Reported')], default='self_reported', max_length=20),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dvs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_health_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Groups animals slaughtered on the same day', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='county_zone',
            field=models.CharField(blank=True, help_text='Assigned county for DVS officers and vets', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dvs_number',
            field=models.CharField(blank=True, help_text='DVS registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cahw_verified',
            field=models.BooleanField(default=False, help_text='CAHW verified by county DVS officer'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('stolen', 'Stolen'), ('sold', 'Sold'), ('slaughtered', 'Slaughtered'), ('deceased', 'Deceased'), ('quarantined', 'Quarantined')], default='alive', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='vet',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['vet', 'cahw']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementpermit',
            name='issued_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['inspector', 'dvs', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Veterinarian'), ('cahw', 'Community Animal Health Worker'), ('dvs', 'County DVS Officer'), ('inspector', 'Inspector'), ('buyer', 'Buyer'), ('abattoir', 'Abattoir'), ('admin', 'Administrator')], default='farmer', max_length=20),
        ),
    ]
