# Generated by Django 6.0.4 on 2026-07-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0005_add_dvs_cahw_stolen_credibility_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age_class',
            field=models.CharField(blank=True, help_text='e.g. calf, weaner, yearling, adult', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed_name',
            field=models.CharField(blank=True, help_text='Free-text breed when no FK breed selected', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, help_text='e.g. cattle, goat, sheep', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CattleTrace.breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('alive', 'Active'), ('stolen', 'Stolen'), ('sold', 'Sold'), ('slaughtered', 'Slaughtered'), ('deceased', 'Dead'), ('quarantined', 'Quarantined')], default='alive', max_length=20),
        ),
    ]
