# Generated by Django 6.0.4 on 2026-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0006_add_species_breed_name_age_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='vet_document',
            field=models.FileField(blank=True, null=True, upload_to='health/vet_docs/'),
        ),
    ]
