# Generated by Django 6.0.4 on 2026-07-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleTrace', '0007_add_vet_document_to_health_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
