from django.urls import path

from . import views


app_name = "cattletrace"

urlpatterns = [
    path("", views.home, name="home"),
    path("owners/", views.owners, name="owners"),
    path("owners/new/", views.owner_create, name="owners_create"),
    path("owners/<str:pk>/", views.owner_detail, name="owners_detail"),
    path("owners/<str:pk>/edit/", views.owner_update, name="owners_update"),
    path("owners/<str:pk>/delete/", views.owner_delete, name="owners_delete"),
    path("holdings/", views.holdings, name="holdings"),
    path("holdings/new/", views.holding_create, name="holdings_create"),
    path("holdings/<str:pk>/", views.holding_detail, name="holdings_detail"),
    path("holdings/<str:pk>/edit/", views.holding_update, name="holdings_update"),
    path("holdings/<str:pk>/delete/", views.holding_delete, name="holdings_delete"),
    path("animals/", views.animals, name="animals"),
    path("animals/new/", views.animal_create, name="animals_create"),
    path("animals/<str:pk>/", views.animal_detail, name="animals_detail"),
    path("animals/<str:pk>/edit/", views.animal_update, name="animals_update"),
    path("animals/<str:pk>/delete/", views.animal_delete, name="animals_delete"),
    path("health-workers/", views.health_workers, name="health_workers"),
    path("health-workers/new/", views.health_worker_create, name="health_workers_create"),
    path("health-workers/<str:pk>/", views.health_worker_detail, name="health_workers_detail"),
    path("health-workers/<str:pk>/edit/", views.health_worker_update, name="health_workers_update"),
    path("health-workers/<str:pk>/delete/", views.health_worker_delete, name="health_workers_delete"),
    path("health-events/", views.health_events, name="health_events"),
    path("health-events/new/", views.health_event_create, name="health_events_create"),
    path("health-events/<str:pk>/", views.health_event_detail, name="health_events_detail"),
    path("health-events/<str:pk>/edit/", views.health_event_update, name="health_events_update"),
    path("health-events/<str:pk>/delete/", views.health_event_delete, name="health_events_delete"),
    path("movements/", views.movements, name="movements"),
    path("movements/new/", views.movement_create, name="movements_create"),
    path("movements/<str:pk>/", views.movement_detail, name="movements_detail"),
    path("movements/<str:pk>/edit/", views.movement_update, name="movements_update"),
    path("movements/<str:pk>/delete/", views.movement_delete, name="movements_delete"),
    path("transactions/", views.transactions, name="transactions"),
    path("transactions/new/", views.transaction_create, name="transactions_create"),
    path("transactions/<str:pk>/", views.transaction_detail, name="transactions_detail"),
    path("transactions/<str:pk>/edit/", views.transaction_update, name="transactions_update"),
    path("transactions/<str:pk>/delete/", views.transaction_delete, name="transactions_delete"),
    path("abattoirs/", views.abattoirs, name="abattoirs"),
    path("abattoirs/new/", views.abattoir_create, name="abattoirs_create"),
    path("abattoirs/<str:pk>/", views.abattoir_detail, name="abattoirs_detail"),
    path("abattoirs/<str:pk>/edit/", views.abattoir_update, name="abattoirs_update"),
    path("abattoirs/<str:pk>/delete/", views.abattoir_delete, name="abattoirs_delete"),
    path("slaughter-records/", views.slaughter_records, name="slaughter_records"),
    path("slaughter-records/new/", views.slaughter_record_create, name="slaughter_records_create"),
    path("slaughter-records/<str:pk>/", views.slaughter_record_detail, name="slaughter_records_detail"),
    path("slaughter-records/<str:pk>/edit/", views.slaughter_record_update, name="slaughter_records_update"),
    path("slaughter-records/<str:pk>/delete/", views.slaughter_record_delete, name="slaughter_records_delete"),
]
